# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'edPet' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for edPet
	pod 'Firebase/Core'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'KDCircularProgress'
    pod 'SwiftGifOrigin', '~> 1.6.1'

  target 'edPetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'edPetUITests' do
    inherit! :search_paths
    # Pods for testing
  end
  

end
